# Generated by Django 4.2.1 on 2023-05-18 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="publication",
            field=models.ForeignKey(
                help_text="The publication that this incident appeared in.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incidents",
                to="db.publication",
            ),
        ),
    ]
