# Generated by Django 4.2.1 on 2023-05-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0002_alter_incident_publication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="aid_type",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Surface aid", "Surface aid"),
                    ("Underground aid", "Underground aid"),
                    ("Body recovery", "Body recovery"),
                    ("Aid on standby", "Aid on standby"),
                    ("Other", "Other"),
                ],
                default="None",
                help_text="The type of aid required.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="fatality",
            field=models.BooleanField(
                default=False,
                help_text="Tick this box if somebody died as a result of this incident. This will also automatically set injury flag when saved.",
            ),
        ),
    ]
