# Generated by Django 4.2.3 on 2023-07-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_alter_incident_aid_type_alter_incident_fatality"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
