# Generated by Django 4.2.3 on 2023-07-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0005_incident_updated_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="editing_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes that will be visible only to people editing this incident on this website. For example: 'need to find the exact date of this incident'. Adding editing notes to an incident will force it to be reviewed and prevent approval.",
            ),
        ),
    ]
