# Generated by Django 4.2.3 on 2023-07-16 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0006_alter_incident_editing_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="multiple_people_involved",
        ),
        migrations.CreateModel(
            name="InjuredCaver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="The first name of the injured caver.", max_length=100
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="The surname of the injured caver.", max_length=100
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        blank=True,
                        help_text="The age of the injured caver at the time of the incident. Can be left blank.",
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        help_text="The gender of the injured caver. Can be left blank.",
                        max_length=10,
                    ),
                ),
                (
                    "injuries",
                    models.CharField(
                        blank=True,
                        help_text="The injuries sustained by the injured caver. Can be left blank.",
                        max_length=200,
                    ),
                ),
                (
                    "injury_areas",
                    models.CharField(
                        blank=True,
                        help_text="The areas of the body that were injured. Can be left blank.",
                        max_length=200,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="injured_cavers",
                        to="db.incident",
                    ),
                ),
            ],
        ),
    ]
