# Generated by Django 4.2.3 on 2023-07-16 13:02

from typing import Any

from django.db import migrations


def move_injured_cavers_to_models(apps: Any, schema_editor: Any,) -> None:
    injuredcaver = apps.get_model("db", "InjuredCaver")
    incident = apps.get_model("db", "Incident")
    for incident in incident.objects.all():
        if not incident.caver_first_name or not incident.caver_surname:
            continue

        injuredcaver.objects.create(
            incident=incident,
            first_name=incident.caver_first_name,
            surname=incident.caver_surname,
            age=incident.caver_age,
            gender=incident.caver_gender,
            injuries=incident.caver_injuries,
            injury_areas=incident.caver_injury_areas,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0007_remove_incident_multiple_people_involved_and_more"),
    ]

    operations = [
        migrations.RunPython(move_injured_cavers_to_models),
    ]
