# Generated by Django 4.2.3 on 2023-07-16 13:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0008_move_injured_cavers_to_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="caver_age",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="caver_first_name",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="caver_gender",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="caver_injuries",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="caver_injury_areas",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="caver_surname",
        ),
    ]
