# Generated by Django 4.2.3 on 2023-07-16 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0009_remove_incident_caver_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="injuredcaver",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("", "Not recorded"), ("Male", "Male"), ("Female", "Female")],
                help_text="The sex of the injured caver.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="injuredcaver",
            name="age",
            field=models.IntegerField(
                blank=True,
                help_text="The age of the injured caver at the time of the incident. Can be left blank.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
