# Generated by Django 4.2.3 on 2023-07-16 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0011_alter_injuredcaver_gender"),
    ]

    operations = []
