# Generated by Django 4.2.3 on 2023-07-16 18:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0012_move_gender_to_sex"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="injuredcaver",
            name="gender",
        ),
    ]
