# Generated by Django 4.2.3 on 2023-07-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0013_remove_injuredcaver_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="injuredcaver",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="The first name of the injured caver.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="injuredcaver",
            name="surname",
            field=models.CharField(
                blank=True,
                help_text="The surname of the injured caver.",
                max_length=100,
            ),
        ),
    ]
