# Generated by Django 4.2.3 on 2023-07-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0014_alter_injuredcaver_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="source",
            field=models.CharField(
                choices=[
                    ("U", "Unknown"),
                    ("C", "Injured caver"),
                    ("P", "Member of injured caver's party"),
                    ("T", "Third party"),
                ],
                default="U",
                help_text="The source of the incident information.",
                max_length=2,
            ),
        ),
    ]
