# Generated by Django 4.2.3 on 2023-07-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0015_incident_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="keywords",
            field=models.CharField(
                blank=True,
                help_text="Any keywords that describe the incident, separated by commas. For example: 'fall, rope, novice'. This field can be completed according to your own judgement and does not need to be consistent across all incidents.",
                max_length=200,
            ),
        ),
    ]
