# Generated by Django 4.2.3 on 2023-07-17 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0016_incident_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="county",
            field=models.CharField(
                blank=True, help_text="Use the full name of the county.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="group_size",
            field=models.IntegerField(
                blank=True,
                help_text="The number of people involved in the incident, excluding any rescue or aid teams.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_type",
            field=models.CharField(
                blank=True,
                help_text="Describe the type of incident. E.g. 'fall', 'drowning', etc.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="primary_cause",
            field=models.CharField(
                blank=True,
                help_text="Briefly describe the primary cause of the incident, for example 'inadequate equipment', 'inexperience', 'poor judgement', etc.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="publication_page",
            field=models.IntegerField(
                blank=True,
                help_text="The page number that this incident appeared on in the publication. This should be taken from the page number in the corner of the PDF.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="secondary_cause",
            field=models.CharField(
                blank=True,
                help_text="Briefly describe the secondary cause of the incident.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="injuredcaver",
            name="age",
            field=models.IntegerField(
                blank=True,
                help_text="The age of the injured caver at the time of the incident.",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="injuredcaver",
            name="injuries",
            field=models.CharField(
                blank=True,
                help_text="The injuries sustained by the injured caver.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="injuredcaver",
            name="injury_areas",
            field=models.CharField(
                blank=True,
                help_text="The areas of the body that were injured.",
                max_length=200,
            ),
        ),
    ]
