# Generated by Django 4.2.3 on 2023-07-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0018_alter_incident_aid_type_alter_incident_group_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="source",
            field=models.CharField(
                choices=[
                    ("Unknown", "Unknown"),
                    ("Injured caver", "Injured caver"),
                    (
                        "Member of injured caver's party",
                        "Member of injured caver's party",
                    ),
                    ("Third party", "Third party"),
                ],
                default="Unknown",
                help_text="The source of the incident information.",
                max_length=50,
            ),
        ),
    ]
