# Generated by Django 4.2.3 on 2023-07-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0019_alter_incident_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="references",
            field=models.TextField(
                blank=True,
                help_text="Any references to external publications or websites.",
            ),
        ),
    ]
