# Generated by Django 4.2.3 on 2023-07-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0023_unapprove_nonstandard_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="incident_type_2",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Rockfall", "Rockfall"),
                    ("Stuck", "Stuck"),
                    ("Lost", "Lost"),
                    ("Stranded", "Stranded"),
                    ("Difficulty on rope", "Difficulty on rope"),
                    ("Equipment problems", "Equipment problems"),
                    ("Hypothermia", "Hypothermia"),
                    ("Lost control on rappel", "Lost control on rappel"),
                    ("Rigging problems", "Rigging problems"),
                    ("Caver fall", "Caver fall"),
                    ("Drowning", "Drowning"),
                    ("Acetylene related", "Acetylene related"),
                    ("Bad air", "Bad air"),
                    ("Illness", "Illness"),
                ],
                default="None",
                help_text="If the incident fits a second type category, enter it here.",
                max_length=100,
                verbose_name="Secondary type",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_type_3",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Rockfall", "Rockfall"),
                    ("Stuck", "Stuck"),
                    ("Lost", "Lost"),
                    ("Stranded", "Stranded"),
                    ("Difficulty on rope", "Difficulty on rope"),
                    ("Equipment problems", "Equipment problems"),
                    ("Hypothermia", "Hypothermia"),
                    ("Lost control on rappel", "Lost control on rappel"),
                    ("Rigging problems", "Rigging problems"),
                    ("Caver fall", "Caver fall"),
                    ("Drowning", "Drowning"),
                    ("Acetylene related", "Acetylene related"),
                    ("Bad air", "Bad air"),
                    ("Illness", "Illness"),
                ],
                default="None",
                help_text="If the incident fits a third type category, enter it here.",
                max_length=100,
                verbose_name="Tertiary type",
            ),
        ),
    ]
