# Generated by Django 4.2.3 on 2023-07-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0026_alter_incident_group_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="state",
            field=models.CharField(
                blank=True, help_text="Use the full name of the state.", max_length=50
            ),
        ),
    ]
