# Generated by Django 4.2.7 on 2023-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0027_alter_incident_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Any additional notes about the incident, as you see fit. This could include information about the incident that is not included in the original text, or any other information that you feel is relevant.",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="original_text",
            field=models.TextField(
                blank=True,
                help_text="The original text of the incident from NSS News. Any references to external publications, such as websites, journals or books, should be removed and placed into the references field below.",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="references",
            field=models.TextField(
                blank=True,
                help_text="Any references to external publications, such as websites, journals or books.",
            ),
        ),
    ]
