# Generated by Django 4.2.7 on 2023-11-14 04:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0028_alter_incident_notes_alter_incident_original_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="pdf_file",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="text_file",
        ),
    ]
