# Generated by Django 4.2.7 on 2023-11-15 21:37

import db.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0029_remove_publication_pdf_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=db.models.publication_upload_path,
                verbose_name="PDF file",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="text_file",
            field=models.FileField(
                blank=True, null=True, upload_to=db.models.publication_upload_path
            ),
        ),
    ]
