# Generated by Django 4.2.7 on 2023-11-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0032_alter_incident_aid_type_alter_incident_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="data_input_source",
            field=models.CharField(
                choices=[("YY", "Unknown"), ("HU", "Human"), ("AI", "AI")],
                default="HU",
                help_text="The source of the data for this incident. If the data was entered by a human, select 'Human'. If the data was generated by an AI, select 'AI'.",
                max_length=2,
            ),
        ),
    ]
