# Generated by Django 4.2.7 on 2023-11-18 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0034_rename_original_text_incident_incident_report"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incident",
            old_name="references",
            new_name="incident_references",
        ),
    ]
