# Generated by Django 4.2.7 on 2023-11-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0035_rename_references_incident_incident_references"),
    ]

    operations = [
        migrations.RenameField(
            model_name="incident",
            old_name="notes",
            new_name="incident_notes",
        ),
        migrations.AddField(
            model_name="incident",
            name="incident_analysis",
            field=models.TextField(blank=True, help_text="Analysis of the incident."),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_report",
            field=models.TextField(
                blank=True,
                help_text="The original text of the incident from NSS News. Any references to external publications, such as websites, journals or books, should be removed and placed into the references field below. Any analysis of the incident should be placed into the analysis field below.",
            ),
        ),
    ]
