# Generated by Django 4.2.7 on 2023-11-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0037_incident_incident_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="keywords",
        ),
        migrations.AlterField(
            model_name="incident",
            name="editing_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes that will be visible only to people editing this incident on this website. For example: 'need to find the exact date of this incident'. Adding editing notes to an incident will force it to be reviewed and prevent approval. These notes will not be visible to the public.",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_analysis",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_notes",
            field=models.TextField(
                blank=True,
                help_text="Any additional notes about the incident, as you see fit. This could include information about the incident that is not included in the original text, or any other information that you feel is relevant.",
                verbose_name="notes",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_references",
            field=models.TextField(blank=True, verbose_name="references"),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_report",
            field=models.TextField(
                blank=True,
                help_text="The text of the incident report from the publication. Any references to external publications, such as websites, journals or books, should be removed and placed into the references field below. Any analysis of the incident should be placed into the analysis field below.",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_summary",
            field=models.TextField(
                blank=True,
                help_text="A short summary of the incident. Maximum 400 characters.",
                max_length=400,
                verbose_name="summary",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("YY", "Unknown"),
                    ("B", "Rockfall"),
                    ("C", "Stuck"),
                    ("D", "Lost"),
                    ("E", "Stranded"),
                    ("F", "Difficulty on rope"),
                    ("G", "Difficulty on ladder"),
                    ("H", "Equipment problems"),
                    ("I", "Hypothermia"),
                    ("J", "Lost control on rappel"),
                    ("K", "Rigging problems"),
                    ("L", "Caver fall"),
                    ("M", "Drowning"),
                    ("N", "Acetylene related"),
                    ("O", "Bad air"),
                    ("P", "Illness"),
                    ("Q", "Injury that does not fit other categories"),
                ],
                default="YY",
                help_text="The primary type of the incident.",
                max_length=2,
                verbose_name="Primary type",
            ),
        ),
    ]
