# Generated by Django 4.2.7 on 2023-11-23 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0039_incident_no_analysis"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="completed",
        ),
    ]
