# Generated by Django 4.2.7 on 2023-11-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0040_remove_incident_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="fatality",
            field=models.BooleanField(
                default=False,
                help_text="Tick this box if somebody died as a result of this incident.",
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="spar",
            field=models.BooleanField(
                default=False,
                help_text="Tick this box if SPAR (self-rescue) techniques were used.",
                verbose_name="SPAR",
            ),
        ),
    ]
