# Generated by Django 4.2.7 on 2023-11-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0042_alter_incident_incident_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="original_text",
            field=models.TextField(
                blank=True,
                help_text="The original text of the incident report from the publication, before any human or AI processing.",
            ),
        ),
    ]
