# Generated by Django 5.0.4 on 2024-04-27 12:16

from django.db import migrations

from db.choices import USStates, Countries


def update_us_state_on_incident(apps, _):
    incident = apps.get_model("db", "Incident")
    states_index = {v: k for k, v in USStates.choices}
    states_index["Tennesee"] = states_index["Tennessee"]

    for i in incident.objects.all():
        if i.country == "United States" or i.country == "USA" or i.country == "US":
            process_us_state(states_index, i)


def process_us_state(states_index, i):
    if i.us_state:
        return

    state = i.state
    if not state:
        return

    if state == "Puerto Rico":
        i.country = Countries.PR
        i.us_state = ""
        i.state = ""
        i.save()
        return

    if state in states_index:
        i.us_state = states_index[state]
        i.state = ""
        i.save()
        return

    if state in USStates:
        i.us_state = state
        i.state = ""
        i.save()
        return

    print(i.id, state, i.us_state)
    raise ValueError(f"Could not find US state for {state}")


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0048_update_country_field_on_incident'),
    ]

    operations = [
        migrations.RunPython(update_us_state_on_incident)
    ]
