version: '3.8'

services:
  db:
    image: postgres:16.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: /app/run.sh devserver
    volumes:
      - ./reportdb/:/app/src/
      - media:/app/mediafiles/
      - static:/app/staticfiles/
    ports:
      - "8000:8000"
    env_file:
      - etc/dev.env
    depends_on:
      - db

volumes:
  media:
  static:
