services:
  db:
    image: postgres:17
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: /app/conf/run.sh devserver
    volumes:
      - ./reportdb/:/app/reportdb/
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - conf/dev.env
    depends_on:
      - db

volumes:
  postgres:
