services:
  web:
    build: .
    command: /app/cidb/conf/run.sh devserver
    restart: unless-stopped
    volumes:
      - ./cidb/:/app/cidb/
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - cidb/conf/dev.env
    depends_on:
      - postgres
      - valkey
    networks:
      - cidb

  postgres:
    image: postgres:18
    restart: unless-stopped
    volumes:
      - ./.postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - cidb

  valkey:
    image: valkey/valkey:latest
    restart: unless-stopped
    volumes:
      - valkey:/var/lib/valkey
    networks:
      - cidb

networks:
  cidb:
    driver: bridge

volumes:
  postgres:
  valkey:
