# Generated by Django 6.0 on 2025-12-28 07:03

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Unique session ID persisted via cookie",
                        unique=True,
                    ),
                ),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                (
                    "ip_addresses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.GenericIPAddressField(),
                        default=list,
                        help_text="IP addresses this visitor has used",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked authenticated user, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        condition=models.Q(("email", ""), _negated=True),
                        name="core_visitor_unique_email_ci",
                    )
                ],
            },
        ),
    ]
