# Generated by Django 6.0 on 2025-12-28 12:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_visitor"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="visitor",
            name="core_visitor_unique_email_ci",
        ),
        migrations.AddField(
            model_name="visitor",
            name="emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254),
                default=list,
                editable=False,
                help_text="Email addresses associated with this visitor",
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="last_seen_at",
            field=models.DateTimeField(
                editable=False, help_text="When this visitor was last seen", null=True
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="request_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, help_text="Total number of requests from this visitor"
            ),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="ip_addresses",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.GenericIPAddressField(),
                default=list,
                editable=False,
                help_text="IP addresses this visitor has used",
            ),
        ),
        migrations.RemoveField(
            model_name="visitor",
            name="email",
        ),
    ]
