# Generated by Django 6.0 on 2025-12-28 13:07

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_visitor_core_visitor_unique_email_ci_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="visitor",
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "emails",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.EmailField(max_length=254),
                        default=list,
                        editable=False,
                        help_text="Email addresses associated with this visitor",
                    ),
                ),
                (
                    "ip_addresses",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.GenericIPAddressField(),
                        default=list,
                        editable=False,
                        help_text="IP addresses this visitor has used",
                    ),
                ),
                (
                    "request_count",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Total number of requests from this visitor",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        editable=False, help_text="When this visitor was last seen", null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked authenticated user, if any",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
