# Generated by Django 6.0 on 2026-01-20 09:16

from typing import Any

from django.db import migrations, models

import cidb.src.core.models.user


def set_is_staff_for_superusers(apps: Any, schema_editor: Any) -> None:
    ACAUser = apps.get_model("core", "ACAUser")
    ACAUser.objects.filter(is_superuser=True).update(is_staff=True)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_make_visitor_pk_uuid7"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="acauser",
            managers=[
                ("objects", cidb.src.core.models.user.ACAUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="acauser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into the admin site.",
                verbose_name="Staff status",
            ),
        ),
        migrations.RunPython(set_is_staff_for_superusers, migrations.RunPython.noop),
    ]
