# Generated by Django 6.0 on 2025-12-28 05:52

import functools
import uuid

import django.db.models.deletion
from django.db import migrations, models

import cidb.src.core.imprecise_date.field
import cidb.src.incidents.models.publication


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField()),
                (
                    "kind",
                    models.CharField(
                        choices=[("individual", "Individual"), ("organization", "Organization")]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GeographicArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[("country", "Country"), ("state", "State"), ("region", "Region")],
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=functools.partial(
                            cidb.src.incidents.models.publication._asset_upload_path, filetype="jpg"
                        ),
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        upload_to=functools.partial(
                            cidb.src.incidents.models.publication._asset_upload_path, filetype="pdf"
                        ),
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("text", ""), _negated=True),
                            models.Q(("image", ""), _negated=True),
                            models.Q(("pdf", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="publication_document_at_least_one_asset",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country_text", models.CharField(max_length=100)),
                ("state_text", models.CharField(blank=True, max_length=100)),
                ("region_text", models.CharField(blank=True, max_length=100)),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True),
                ),
                (
                    "canonical_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="incidents.geographicarea",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(default="Unknown Cave")),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cave",
                        to="incidents.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("non-binary", "Non-binary"),
                            ("genderfluid", "Genderfluid"),
                            ("agender", "Agender"),
                        ],
                        default="",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="incidents.geographicarea",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, max_length=255)),
                (
                    "published_at",
                    cidb.src.core.imprecise_date.field.ImpreciseDateField(max_length=11),
                ),
                (
                    "authors",
                    models.ManyToManyField(related_name="publications", to="incidents.author"),
                ),
                (
                    "content",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication",
                        to="incidents.document",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("date", cidb.src.core.imprecise_date.field.ImpreciseDateField(max_length=11)),
                ("time", models.TimeField(blank=True, null=True)),
                ("report", models.TextField(blank=True)),
                ("analysis", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "cave",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="incidents.cave",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_incidents",
                        to="incidents.publication",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="incidents", to="incidents.tag"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublicationPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField()),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication_page",
                        to="incidents.document",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="incidents.publication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IncidentReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="incidents.incident",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incident_references",
                        to="incidents.publication",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incident_references",
                        to="incidents.publicationpage",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                    ("latitude__isnull", True),
                    _connector="OR",
                ),
                name="incidents_location_valid_latitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                    ("longitude__isnull", True),
                    _connector="OR",
                ),
                name="incidents_location_valid_longitude",
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationpage",
            constraint=models.UniqueConstraint(
                fields=("number", "publication"),
                name="publication_page_unique_number_per_publication",
            ),
        ),
        migrations.AddConstraint(
            model_name="incidentreference",
            constraint=models.UniqueConstraint(
                fields=("incident", "publication", "page"),
                name="incidents_incidentreference_unique_incident_publication_page",
            ),
        ),
    ]
