# Generated by Django 6.0 on 2025-12-28 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_visitor"),
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("inaccurate", "Inaccurate Information"),
                            ("incomplete", "Missing Information"),
                            ("duplicate", "Duplicate Entry"),
                            ("typo", "Typographical Error"),
                            ("formatting", "Formatting Error"),
                            ("privacy", "Privacy Concern"),
                            ("offensive", "Offensive Content"),
                            ("other", "Other"),
                        ]
                    ),
                ),
                ("description", models.TextField(help_text="Detailed description of the issue")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(blank=True, help_text="Internal notes from reviewer"),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_reports",
                        to="incidents.incident",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_reports",
                        to="core.visitor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
