# Generated by Django 6.0 on 2025-12-28 07:28

import uuid

import django.db.models.deletion
from django.db import migrations, models

import cidb.src.core.imprecise_date.field


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_contentreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("age_at_incident", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Injury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SourceExtract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="SourceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="incidentreference",
            name="incidents_incidentreference_unique_incident_publication_page",
        ),
        migrations.AddField(
            model_name="incidentreference",
            name="author",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="incidentreference",
            name="index",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="incidentreference",
            name="raw_citation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="incidentreference",
            name="reference_date",
            field=cidb.src.core.imprecise_date.field.ImpreciseDateField(
                default="2025",
                max_length=11,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="incidentreference",
            name="source",
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name="incidentreference",
            name="title",
            field=models.CharField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="incidentreference",
            constraint=models.UniqueConstraint(
                fields=("incident", "index"), name="incidents_incidentreference_unique_index"
            ),
        ),
        migrations.AddField(
            model_name="incidentperson",
            name="incident",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="persons_involved",
                to="incidents.incident",
            ),
        ),
        migrations.AddField(
            model_name="incidentperson",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="incident_involvements",
                to="incidents.person",
            ),
        ),
        migrations.AddField(
            model_name="incidentperson",
            name="injuries",
            field=models.ManyToManyField(
                blank=True, related_name="persons_injured", to="incidents.injury"
            ),
        ),
        migrations.AddField(
            model_name="incident",
            name="source_extract",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incident",
                to="incidents.sourceextract",
            ),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_file",
                to="incidents.document",
            ),
        ),
        migrations.AddField(
            model_name="sourcefile",
            name="publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="source_files",
                to="incidents.publication",
            ),
        ),
        migrations.AddField(
            model_name="sourceextract",
            name="source_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracts",
                to="incidents.sourcefile",
            ),
        ),
        migrations.RemoveField(
            model_name="incidentreference",
            name="page",
        ),
        migrations.RemoveField(
            model_name="incidentreference",
            name="publication",
        ),
        migrations.AddConstraint(
            model_name="incidentperson",
            constraint=models.UniqueConstraint(
                fields=("incident", "person"),
                name="incidents_incidentperson_unique_incident_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceextract",
            constraint=models.UniqueConstraint(
                fields=("source_file", "sequence"),
                name="incidents_sourceextract_unique_source_sequence",
            ),
        ),
    ]
