# Generated by Django 6.0 on 2025-12-28 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0003_incidentperson_injury_sourceextract_sourcefile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataOperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("operation_name", models.CharField(max_length=100)),
                ("operation_version", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("skipped", "Skipped"),
                            ("error", "Error"),
                            ("no_change", "No Change"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("changes_made", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_logs",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["incident", "operation_name"], name="incidents_d_inciden_7323bf_idx"
                    ),
                    models.Index(
                        fields=["operation_name", "created_at"],
                        name="incidents_d_operati_9e8ce3_idx",
                    ),
                ],
            },
        ),
    ]
