# Generated by Django 6.0 on 2025-12-28 12:12

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0004_dataoperationlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        help_text="Normalized (lowercase, stripped) search query",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "query_count",
                    models.PositiveBigIntegerField(
                        default=1, help_text="Number of times this query has been searched"
                    ),
                ),
                (
                    "last_queried_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this query was last searched",
                    ),
                ),
            ],
            options={
                "verbose_name": "search query",
                "verbose_name_plural": "search queries",
            },
        ),
        migrations.CreateModel(
            name="DuplicateGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("confirmed", "Confirmed Duplicate"),
                            ("rejected", "Not a Duplicate"),
                            ("merged", "Merged"),
                        ],
                        default="pending",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "primary_incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_of_groups",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IncidentEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "embedding",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(), size=1536
                    ),
                ),
                (
                    "model_version",
                    models.CharField(default="text-embedding-3-small", max_length=50),
                ),
                (
                    "incident",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DuplicateGroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("similarity_score", models.FloatField()),
                ("llm_confidence", models.IntegerField(blank=True, null=True)),
                ("llm_reasoning", models.TextField(blank=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="incidents.duplicategroup",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_memberships",
                        to="incidents.incident",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "incident"),
                        name="incidents_duplicategroupmember_unique_group_incident",
                    )
                ],
            },
        ),
    ]
