# Generated by Django 6.0 on 2025-12-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0005_duplicategroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times this incident has been viewed"
            ),
        ),
    ]
