# Generated by Django 6.0 on 2025-12-28 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0006_incident_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentreport",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_reports",
                to="incidents.incident",
            ),
        ),
    ]
