# Generated by Django 6.0 on 2025-12-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_make_visitor_pk_uuid7"),
        ("incidents", "0007_allow_null_incident_on_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contentreport",
            name="reporter",
        ),
        migrations.AddField(
            model_name="contentreport",
            name="reporter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_reports",
                to="core.visitor",
            ),
        ),
    ]
