# Generated by Django 6.0 on 2025-12-28 16:35
from typing import Any

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.apps.registry import Apps
from django.db import migrations


def populate_search_vectors(apps: Apps, schema_editor: Any) -> None:
    from django.contrib.postgres.search import SearchVector

    Incident = apps.get_model("incidents", "Incident")
    Incident.objects.update(
        search_vector=SearchVector("title", weight="A")
        + SearchVector("summary", weight="B")
        + SearchVector("report", weight="C")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0008_recreate_reporter_fk_for_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="incidents_i_search__b25ef2_gin"
            ),
        ),
        migrations.RunPython(populate_search_vectors, migrations.RunPython.noop),
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION incidents_search_vector_trigger()
            RETURNS trigger AS $$
            BEGIN
                NEW.search_vector :=
                    setweight(to_tsvector('english', COALESCE(NEW.title, '')), 'A') ||
                    setweight(to_tsvector('english', COALESCE(NEW.summary, '')), 'B') ||
                    setweight(to_tsvector('english', COALESCE(NEW.report, '')), 'C');
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS incidents_search_vector_update ON incidents_incident;
            CREATE TRIGGER incidents_search_vector_update
            BEFORE INSERT OR UPDATE OF title, summary, report
            ON incidents_incident
            FOR EACH ROW
            EXECUTE FUNCTION incidents_search_vector_trigger();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS incidents_search_vector_update ON incidents_incident;
            DROP FUNCTION IF EXISTS incidents_search_vector_trigger();
            """,
        ),
    ]
