# Generated by Django 6.0 on 2026-01-20 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0010_search_improvements"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="incident",
            name="incidents_incident_date_cave",
        ),
        migrations.RemoveIndex(
            model_name="incident",
            name="incidents_incident_origin_date",
        ),
        migrations.AddField(
            model_name="contentreport",
            name="url",
            field=models.URLField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name="cave",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="caves",
                to="incidents.location",
            ),
        ),
        migrations.AlterField(
            model_name="searchclick",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="searchclick",
            name="position",
            field=models.PositiveSmallIntegerField(
                help_text="Position in search results (1-indexed)"
            ),
        ),
        migrations.AddIndex(
            model_name="cave",
            index=models.Index(fields=["name"], name="incidents_cave_name"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["view_count"], name="incidents_incident_view_count"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["origin"], name="incidents_incident_origin"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(fields=["date"], name="incidents_incident_date"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["country_text"], name="incidents_location_country"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["state_text"], name="incidents_location_state"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["region_text"], name="incidents_location_region"),
        ),
    ]
