from typing import Any, Self

from django.db import models
from django.db.models import Manager
from treebeard.exceptions import (
    InvalidMoveToDescendant as InvalidMoveToDescendant,
)
from treebeard.exceptions import (
    NodeAlreadySaved as NodeAlreadySaved,
)
from treebeard.models import BulkDict, MovePos, Node, SiblingPos

def get_result_class[T: Node](cls: type[T]) -> type[T]: ...

class AL_NodeManager[T: models.Model](Manager[T]):
    def get_queryset(self) -> models.QuerySet[T, T]: ...

class AL_Node(Node):
    parent: Self | None
    sib_order: int
    @classmethod
    def add_root(cls, **kwargs: Any) -> Self: ...
    @classmethod
    def get_root_nodes(cls) -> models.QuerySet[Self, Self]: ...
    def get_depth(self, update: bool = False) -> int: ...
    def get_children(self) -> models.QuerySet[Self, Self]: ...
    def get_parent(self, update: bool = False) -> Self | None: ...
    def get_ancestors(self) -> list[Self]: ...
    def get_root(self) -> Self: ...
    def is_descendant_of(self, node: Self) -> bool: ...
    @classmethod
    def dump_bulk(cls, parent: Self | None = None, keep_ids: bool = True) -> list[BulkDict]: ...
    def add_child(self, **kwargs: Any) -> Self: ...
    @classmethod
    def get_tree(cls, parent: Self | None = None) -> list[Self]: ...
    def get_descendants(self, include_self: bool = False) -> list[Self]: ...
    def get_descendant_count(self) -> int: ...
    def get_siblings(self) -> models.QuerySet[Self, Self]: ...
    def add_sibling(self, pos: SiblingPos | None = None, **kwargs: Any) -> Self: ...
    def move(self, target: Self, pos: MovePos | None = None) -> None: ...
