from collections.abc import Iterable, Mapping, Sequence
from typing import Any, ClassVar, Literal, Self, TypedDict

from django.db.models import Model, QuerySet
from treebeard.exceptions import (
    InvalidPosition as InvalidPosition,
)
from treebeard.exceptions import (
    MissingNodeOrderBy as MissingNodeOrderBy,
)

SiblingPos = Literal["first-sibling", "left", "right", "last-sibling", "sorted-sibling"]
MovePos = Literal[
    "first-sibling",
    "left",
    "right",
    "last-sibling",
    "sorted-sibling",
    "first-child",
    "last-child",
    "sorted-child",
]

class BulkDict(TypedDict, total=False):
    data: Mapping[str, Any]
    children: list[BulkDict]

class InfoDict(TypedDict):
    open: bool
    close: list[int]
    level: int

class Node(Model):
    node_order_by: ClassVar[Sequence[str]]

    @classmethod
    def add_root(cls, **kwargs: Any) -> Self: ...
    @classmethod
    def get_foreign_keys(cls) -> dict[str, type[Model]]: ...
    @classmethod
    def load_bulk(
        cls, bulk_data: list[BulkDict], parent: Self | None = None, keep_ids: bool = False
    ) -> list[Any]: ...
    @classmethod
    def dump_bulk(cls, parent: Self | None = None, keep_ids: bool = True) -> list[BulkDict]: ...
    @classmethod
    def get_root_nodes(cls) -> QuerySet[Self, Self]: ...
    @classmethod
    def get_first_root_node(cls) -> Self | None: ...
    @classmethod
    def get_last_root_node(cls) -> Self | None: ...
    @classmethod
    def find_problems(cls) -> Any: ...
    @classmethod
    def fix_tree(cls) -> None: ...
    @classmethod
    def get_tree(cls, parent: Self | None = None) -> QuerySet[Self, Self] | list[Self]: ...
    @classmethod
    def get_descendants_group_count(cls, parent: Self | None = None) -> list[Self]: ...
    def get_depth(self) -> int: ...
    def get_siblings(self) -> QuerySet[Self, Self]: ...
    def get_children(self) -> QuerySet[Self, Self]: ...
    def get_children_count(self) -> int: ...
    def get_descendants(self) -> QuerySet[Self, Self] | list[Self]: ...
    def get_descendant_count(self) -> int: ...
    def get_first_child(self) -> Self | None: ...
    def get_last_child(self) -> Self | None: ...
    def get_first_sibling(self) -> Self: ...
    def get_last_sibling(self) -> Self: ...
    def get_prev_sibling(self) -> Self | None: ...
    def get_next_sibling(self) -> Self | None: ...
    def is_sibling_of(self, node: Self) -> bool: ...
    def is_child_of(self, node: Self) -> bool: ...
    def is_descendant_of(self, node: Self) -> bool: ...
    def add_child(self, **kwargs: Any) -> Self: ...
    def add_sibling(self, pos: SiblingPos | None = None, **kwargs: Any) -> Self: ...
    def get_root(self) -> Self: ...
    def is_root(self) -> bool: ...
    def is_leaf(self) -> bool: ...
    def get_ancestors(self) -> QuerySet[Self, Self] | list[Self]: ...
    def get_parent(self, update: bool = False) -> Self | None: ...
    def move(self, target: Self, pos: MovePos | None = None) -> None: ...
    def delete(
        self, using: str | None = ..., keep_parents: bool = ...
    ) -> tuple[int, dict[str, int]]: ...
    def get_sorted_pos_queryset(
        self, siblings: QuerySet[Self, Self], newobj: Self
    ) -> QuerySet[Self, Self]: ...
    def refresh_from_db(
        self,
        using: str | None = None,
        fields: Iterable[str] | None = None,
        from_queryset: QuerySet[Self] | None = None,
    ) -> None: ...
    @classmethod
    def get_annotated_list_qs(
        cls, qs: QuerySet[Self, Self] | list[Self]
    ) -> list[tuple[Self, InfoDict]]: ...
    @classmethod
    def get_annotated_list(
        cls, parent: Self | None = None, max_depth: int | None = None
    ) -> list[tuple[Self, InfoDict]]: ...
    @classmethod
    def get_database_vendor(cls, action: Literal["read", "write"]) -> str: ...
