from typing import Any, Literal, Self

from django.db import models
from treebeard.exceptions import (
    InvalidMoveToDescendant as InvalidMoveToDescendant,
)
from treebeard.exceptions import (
    NodeAlreadySaved as NodeAlreadySaved,
)
from treebeard.exceptions import (
    PathOverflow as PathOverflow,
)
from treebeard.models import BulkDict, Node
from treebeard.numconv import NumConv as NumConv

SiblingPos = Literal["first-sibling", "left", "right", "last-sibling", "sorted-sibling"]
MovePos = Literal[
    "first-sibling",
    "left",
    "right",
    "last-sibling",
    "sorted-sibling",
    "first-child",
    "last-child",
    "sorted-child",
]

def sql_concat(*args: str, vendor: str | None = None) -> str: ...
def sql_length(field: str, vendor: str | None = None) -> str: ...
def sql_substr(
    field: str, pos: str, length: str | None = None, vendor: str | None = None
) -> str: ...
def get_result_class[T: Node](cls: type[T]) -> type[T]: ...

class MP_NodeQuerySet[T: models.Model](models.query.QuerySet[T, T]):
    def delete(self, *args: Any, **kwargs: Any) -> tuple[int, dict[str, int]]: ...

class MP_NodeManager[T: models.Model](models.Manager[T]):
    def get_queryset(self) -> MP_NodeQuerySet[T]: ...

class MP_AddHandler:
    stmts: list[tuple[str, list[Any]]]
    def __init__(self) -> None: ...

class MP_ComplexAddMoveHandler(MP_AddHandler):
    node_cls: type[MP_Node]
    def run_sql_stmts(self) -> None: ...
    def get_sql_update_numchild(self, path: str, incdec: str = "inc") -> tuple[str, list[str]]: ...
    def reorder_nodes_before_add_or_move(
        self,
        pos: str,
        newpos: int | None,
        newdepth: int,
        target: MP_Node,
        siblings: models.QuerySet[Any, Any] | list[Any],
        oldpath: str | None = None,
        movebranch: bool = False,
    ) -> tuple[str | None, str]: ...
    def get_sql_newpath_in_branches(self, oldpath: str, newpath: str) -> tuple[str, list[Any]]: ...

class MP_AddRootHandler(MP_AddHandler):
    cls: type[MP_Node]
    kwargs: dict[str, Any]
    def __init__(self, cls: type[MP_Node], **kwargs: Any) -> None: ...
    def process(self) -> MP_Node: ...

class MP_AddChildHandler(MP_AddHandler):
    node: MP_Node
    node_cls: type[MP_Node]
    kwargs: dict[str, Any]
    def __init__(self, node: MP_Node, **kwargs: Any) -> None: ...
    def process(self) -> MP_Node: ...

class MP_AddSiblingHandler(MP_ComplexAddMoveHandler):
    node: MP_Node
    node_cls: type[MP_Node]
    pos: str
    kwargs: dict[str, Any]
    def __init__(self, node: MP_Node, pos: str | None, **kwargs: Any) -> None: ...
    def process(self) -> MP_Node: ...

class MP_MoveHandler(MP_ComplexAddMoveHandler):
    node: MP_Node
    node_cls: type[MP_Node]
    target: MP_Node
    pos: str | None
    def __init__(self, node: MP_Node, target: MP_Node, pos: str | None = None) -> None: ...
    def process(self) -> None: ...
    def sanity_updates_after_move(self, oldpath: str, newpath: str) -> None: ...
    def update_move_to_child_vars(self) -> tuple[int, list[Any], int | None]: ...
    def get_mysql_update_depth_in_branch(self, path: str) -> tuple[str, list[Any]]: ...

class MP_Node(Node):
    steplen: int
    alphabet: str
    path: str
    depth: int
    numchild: int
    numconv_obj_: NumConv | None
    @classmethod
    def numconv_obj(cls) -> NumConv: ...
    @classmethod
    def add_root(cls, **kwargs: Any) -> Self: ...
    @classmethod
    def dump_bulk(cls, parent: Self | None = None, keep_ids: bool = True) -> list[BulkDict]: ...
    @classmethod
    def find_problems(cls) -> tuple[list[Any], list[Any], list[Any], list[Any], list[Any]]: ...
    @classmethod
    def fix_tree(cls, destructive: bool = False, fix_paths: bool = False) -> None: ...
    @classmethod
    def get_tree(cls, parent: Self | None = None) -> MP_NodeQuerySet[Self]: ...
    @classmethod
    def get_root_nodes(cls) -> MP_NodeQuerySet[Self]: ...
    @classmethod
    def get_descendants_group_count(cls, parent: Self | None = None) -> list[Self]: ...
    def get_depth(self) -> int: ...
    def get_siblings(self) -> MP_NodeQuerySet[Self]: ...
    def get_children(self) -> MP_NodeQuerySet[Self]: ...
    def get_next_sibling(self) -> Self | None: ...
    def get_descendants(self, include_self: bool = False) -> MP_NodeQuerySet[Self]: ...
    def get_prev_sibling(self) -> Self | None: ...
    def get_children_count(self) -> int: ...
    def is_sibling_of(self, node: Self) -> bool: ...
    def is_child_of(self, node: Self) -> bool: ...
    def is_descendant_of(self, node: Self) -> bool: ...
    def add_child(self, **kwargs: Any) -> Self: ...
    def add_sibling(self, pos: SiblingPos | None = None, **kwargs: Any) -> Self: ...
    def get_root(self) -> Self: ...
    def is_root(self) -> bool: ...
    def is_leaf(self) -> bool: ...
    def get_ancestors(self) -> MP_NodeQuerySet[Self]: ...
    def get_parent(self, update: bool = False) -> Self | None: ...
    def move(self, target: Self, pos: MovePos | None = None) -> None: ...
