# Generated by Django 4.2.3 on 2023-07-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editlog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="editlogentry",
            name="verb",
            field=models.CharField(
                choices=[
                    ("added", "added"),
                    ("edited", "edited"),
                    ("deleted", "deleted"),
                ],
                default="edited",
                max_length=20,
            ),
        ),
    ]
