# Generated by Django 4.2.3 on 2023-07-20 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0020_alter_incident_references"),
        ("editlog", "0002_editlogentry_verb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editlogentry",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="db.incident",
            ),
        ),
    ]
