# Generated by Django 4.2.3 on 2023-07-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("editlog", "0003_alter_editlogentry_incident"),
    ]

    operations = [
        migrations.AddField(
            model_name="editlogentry",
            name="incident_name",
            field=models.CharField(default="Deleted incident", max_length=200),
            preserve_default=False,
        ),
    ]
