name: Lint

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: Ruff
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Run ruff
        uses: chartboost/ruff-action@v1
        with:
          args: check --verbose
