name: Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  run-tests:
    name: Django tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      PYTHONPATH: ${{ github.workspace }}
      BASE_DIR: ${{ github.workspace }}/reportdb

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Django tests
        working-directory: ${{ env.BASE_DIR }}
        run: |
          python manage.py test

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
